version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - monitoring-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - monitoring-network

  pinger:
    build: ./pinger
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - backend
    networks:
      - monitoring-network

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: monitoring
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - monitoring-network

volumes:
  postgres-data:

networks:
  monitoring-network:
    driver: bridge